MQTT_SERVER_ADDRESS = "192.168.1.49"
MQTT_SERVER_PORT = 1883

DRIVER_STATUS_FORWARD = "turn_forward"
DRIVER_STATUS_BACK = "turn_back"
DRIVER_STATUS_LEFT = "turn_left"
DRIVER_STATUS_RIGHT = "turn_right"
DRIVER_STATUS_STOP = "stop"
DRIVER_STATUS_EXIT = "exit"
DRIVER_STATUS_TURN_OPPOSITE = "opposite"
DRIVER_STATUS_TURN_LEFT = "left"
DRIVER_STATUS_TURN_RIGHT = "right"

TURN_TIME = 0.22

TOPIC_SUBSCRIBE_TO_EV3 = "MESSAGE_TO_EV3_CLIENT"
TOPIC_SUBSCRIBE_FROM_EV3 = "MESSAGE_FROM_EV3_CLIENT"

DIFFER_SENSOR_RATE = 4/3